import initScrollSuave from "./modules/scroll-suave.js";
import initScrollAnimation from "./modules/scroll-animation.js";
import initAccordionList from "./modules/accordion-list.js";
import initTabNav from "./modules/tabnav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMobileMenu from "./modules/mobile-menu.js";
import initWorkingTime from "./modules/workingTime.js";
import initFetchGatos from "./modules/fetch-gatos.js";
import initFetchBtc from "./modules/fetch-btc.js";

initFetchGatos();
initScrollSuave();
initScrollAnimation();
initAccordionList();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMobileMenu();
initWorkingTime();
initFetchBtc();
